@startuml
skinparam nodesep 15
skinparam ranksep 25

usecase "start" as start_node
usecase " " as n1
usecase " " as n2
usecase " " as n3
usecase "d(oldStatus)" as n4
usecase " " as n5
usecase " " as n6
usecase " " as n7
usecase " " as n8
usecase " " as n9
usecase " " as n10
usecase " " as n11
usecase " " as n12
usecase " " as n13
usecase " " as n14
usecase " " as n15
usecase " " as n16
usecase " " as n17
usecase " " as n18
usecase " " as n19
usecase " " as n20
usecase " " as n21
usecase " " as n22
usecase " " as n23
usecase " " as n24
usecase " " as n25
usecase " " as n26
usecase "u(oldStatus)" as n27
usecase " " as n28
usecase " " as n29
usecase " " as n30
usecase " " as n31
usecase " " as n32
usecase "u(oldStatus)" as n33
usecase "u(oldStatus)" as n34
usecase " " as n35
usecase " " as n36
usecase " " as n37
usecase " " as n38
usecase " " as n39
usecase " " as n40
usecase " " as n41
usecase " " as n42
usecase " " as n43
usecase " " as n44
usecase " " as n45
usecase " " as n46
usecase " " as n47
usecase " " as n48
usecase " " as n49
usecase " " as n50
usecase " " as n51
usecase " " as n52
usecase " " as n53
usecase " " as n54
usecase "Exit" as end_node

note right of end_node : k(oldStatus)

start_node --> n1
n1 --> n2
n2 --> n3 : true
n2 --> n4 : false
n3 --> end_node

n4 --> n5
n5 --> n6
n6 --> n7 : true
n6 --> n8 : false
n7 --> n8

n8 --> n9 : true
n8 --> n10 : false
n9 --> n11
n10 --> n11

n11 --> n12
n12 --> n13 : case PREPARING
n12 --> n14 : case SHIPPING
n12 --> n15 : case DELIVERED
n12 --> n16 : case SUCCESS
n12 --> n17 : case CANCELLED
n12 --> n18 : case RETURNED
n12 --> n19 : default

n13 --> n19
n14 --> n19
n15 --> n19
n16 --> n19
n17 --> n19
n18 --> n19

n19 --> n20
n20 --> n22 : true
n20 --> n21 : false
n21 --> n22

n22 --> n23
n23 --> n24 : true
n23 --> n25 : false
n24 --> n25

n25 --> n26
n26 --> n27 : true
n26 --> n30 : false
n27 --> n28 : true
n27 --> n30 : false

n28 --> n29 : true
n28 --> n30 : false
n29 --> n28

n30 --> n32 : true
n30 --> n31 : false
n31 --> n32 : true
n31 --> n37 : false

n32 --> n33
n33 --> n34 : true
n33 --> n37 : false
n34 --> n35 : true
n34 --> n37 : false

n35 --> n36 : true
n35 --> n37 : false
n36 --> n35

n37 --> n38
n38 --> n39 : case PREPARING
n38 --> n40 : case SHIPPING
n38 --> n41 : case DELIVERED
n38 --> n42 : case SUCCESS
n38 --> n43 : case CANCELLED
n38 --> n44 : case RETURNED
n38 --> n45 : default

n39 --> n46
n40 --> n46
n41 --> n46
n42 --> n46
n43 --> n46
n44 --> n46
n45 --> n46

n46 --> n47 : true
n46 --> n48 : false
n47 --> n49
n48 --> n49

n49 --> n50
n50 --> n51 : true
n50 --> n54 : false
n51 --> n52 : true
n51 --> n54 : false

n52 --> n53
n53 --> n54
n54 --> end_node

@enduml
